name: CI

on: [push, pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        yarn install
        yarn build
    - name: Test
      run: yarn test
